apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  labels:
    app: sample-app
    env: prod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample-app
      env: prod
  template:
    metadata:
      name: sample-app-pod
      labels:
        app: sample-app
        env: prod
    spec:
      containers:
        - name: redis
          image: redis
        - name: sample-app
          image: ponceps/sample-app:v1
          imagePullPolicy: Always
